---
kind: pipeline
type: docker
name: Target build
platform:
  os: linux
  arch: amd64

steps:
- name: Tests
  image: rust:latest

  commands:
    - cd workspace
    - cargo test

- name: Target build
  image: rust:latest

  commands:
    - rustup target add thumbv6m-none-eabi
    - cd workspace/cross_compile
    - cargo install flip-link 
    - cargo build
  depends_on:
    - Tests

- name: Upload binaries
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/cross_compile/target/thumbv6m-none-eabi/debug/robotic_arm
    target: Robotic_Arm/binaries/development/build_$${DRONE_BUILD_NUMBER}_binary
    insecure: true
  depends_on:
    - Target build

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: Deploy
platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: rust:latest

  commands:
    - rustup target add thumbv6m-none-eabi
    - cd workspace/cross_compile
    - cargo install flip-link 
    - cargo build --release

- name: Upload binaries
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/cross_compile/target/thumbv6m-none-eabi/release/robotic_arm
    target: Robotic_Arm/binaries/deployment/build_$${DRONE_BUILD_NUMBER}_binary
    flat: true
    insecure: true
  depends_on:
    - Build

trigger:
  event:
  - promote
  target:
  - RoboticArm
